version: '3'
services:
  auth_nginx:
    image: nginx:stable-alpine
    container_name: nginx_auth
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_php
    networks:
      - laravel

  auth_php:
    build:
      context: .
    image: auth:v1.0.0
    container_name: auth_app
    volumes:
      - ./src:/var/www/html
    ports:
      - 9001:80
    networks:
      - laravel

networks:
  laravel:
